config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  
  devise_for :users

  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

  namespace :api do
    resources :books, only: [:index, :show, :create, :update, :destroy] do
      collection do
        get 'search'
      end
    end

    resources :borrowings, only: [:index, :show, :create, :update, :destroy]
    
    post 'borrowings/:id/return', to: 'borrowings#return', as: 'return_borrowing'
    get 'dashboard', to: 'dashboard#index', as: 'dashboard_index'
  end

  resources :borrowings
  resources :books

  resources :borrowings do
    member do
      patch 'return'
    end
  end

  post "remove_book" => "book#remove_book"
  get "books/:book_id/borrowings", to: "books#borrowings", as: 'book_borrowings'
  get "borrowings/:id/return", to: "borrowings#return", as: 'borrowing_return'

  # For Librarians
  get '/librarian/dashboard', to: 'librarians#dashboard'
  get '/librarian/logout', to: 'librarians#logout', as: :librarian_logout

  # For Members
  get '/member/dashboard', to: 'members#dashboard'
  get '/member/logout', to: 'members#logout', as: :member_logout
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title, presence: true
    validates :author, presence: true
    validates :genre, presence: true
    validates :isbn, presence: true, uniqueness: true
    validates :total_copies, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  
    has_many :borrowings, dependent: :destroy
  
    # Scope for searching books
    scope :search, ->(query) {
      where('title LIKE ? OR author LIKE ? OR genre LIKE ?', "%#{query}%", "%#{query}%", "%#{query}%")
    }

    scope :available_for_borrow, -> { where('total_copies > ?', Borrowing.where(book_id: self.ids, returned_at: nil).count) }
    
    def currrently_borrowed
      borrowings.where(returned_at: nil).count
    end

    def all_time_borrowed
      borrowings.count
    end

    def available_copies
      total_copies - currrently_borrowed
    end
  end

app/controllers/api/books_controller.rb
class Api::BooksController < ApplicationController
    before_action :authenticate_user!, only: [:create, :update, :destroy]
    before_action :authorize_librarian, only: [:create, :update, :destroy]
  
    def index
      books = Book.all
      render json: books
    end
  
    def show
      book = Book.find(params[:id])
      render json: book
    end
  
    def create
      book = Book.new(book_params)
  
      if book.save
        render json: book, status: :created
      else
        render json: { errors: book.errors.full_messages }, status: :unprocessable_entity
      end
    end
  
    def update
      book = Book.find(params[:id])
  
      if book.update(book_params)
        render json: book
      else
        render json: { errors: book.errors.full_messages }, status: :unprocessable_entity
      end
    end
  
    def destroy
      book = Book.find(params[:id])
      book.destroy
      head :no_content
    end
  
    def search
      title = params[:title]
      author = params[:author]
      genre = params[:genre]
  
      books = Book.all
  
      books = books.where('title ILIKE ?', "%#{title}%") if title.present?
      books = books.where('author ILIKE ?', "%#{author}%") if author.present?
      books = books.where('genre ILIKE ?', "%#{genre}%") if genre.present?
  
      render json: books
    end

    private
  
    def book_params
      params.require(:book).permit(:title, :author, :genre, :isbn, :total_copies)
    end
  
    def authorize_librarian
      return if current_user.librarian?
  
      render json: { error: 'You are not authorized to perform this action.' }, status: :unauthorized
    end
  end
  

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_librarian, except: [:index, :show]

  def index
    @current_user = current_user
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end
  
  def remove_book
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, notice: 'Book was successfully deleted.'
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    redirect_to books_path, notice: 'Book was successfully destroyed.'
  end

  def borrowings
    @book = Book.find(params[:book_id])
    @borrowings = @book.borrowings
  end

  def search
    title = params[:title]
    author = params[:author]
    genre = params[:genre]

    books = Book.all

    books = books.where('title ILIKE ?', "%#{title}%") if title.present?
    books = books.where('author ILIKE ?', "%#{author}%") if author.present?
    books = books.where('genre ILIKE ?', "%#{genre}%") if genre.present?

    @books = books
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :genre, :isbn, :total_copies)
  end

  def authorize_librarian
    redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user.librarian?
  end
end

app/views/books/borrowings.html.erb
<div class="container mt-5">
  <h1>Borrowings for <%= @book.title %></h1>
  <hr>
  <div class="d-flex justify-content-end mb-5">
    <span class="text-muted mt-2 mr-3">Hi! <%= @current_user.role.capitalize() %> <%= @current_user.email %></span>
    <%= link_to 'Back to Manage Books', books_path, class: 'btn btn-primary mr-2' %>
    <%= link_to 'Librarian Dashboard', librarian_dashboard_path, class: 'btn btn-success mr-2' %>
    <%= link_to 'Logout', librarian_logout_path, method: :delete, class: 'btn btn-danger' %>
  </div>

  <% if @borrowings.empty? %>
    <p>No borrowings for this book.</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>Borrowed By:</th>
          <th>Borrowed At:</th>
          <th>Returned At:</th>
          <th>Return Book:</th>
        </tr>
      </thead>
      <tbody>
        <% @borrowings.each do |borrowing| %>
          <tr>
            <td><%= borrowing.user.email %></td>
            <td><%= borrowing.borrowed_at %></td>
            <td><%= borrowing.returned_at || 'Not returned' %></td>
            <td>
              <% if borrowing.returned_at.nil? %>
                <%= link_to 'Return Book', return_borrowing_path(borrowing), class: 'btn btn-success btn-sm', method: :post %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Edit <%= @book.title %></h1>

  <%= form_with(model: @book, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :author %>
      <%= form.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :genre %>
      <%= form.text_field :genre, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :isbn %>
      <%= form.text_field :isbn, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :total_copies %>
      <%= form.number_field :total_copies, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit 'Update Book', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', book_path(@book), class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/books/index.html.erb
<div class="container mt-5">
  <h1>Book Inventory</h1>
  <hr>
  <div class="d-flex justify-content-end mb-5">
    <span class="text-muted mt-2 mr-3">Hi! <%= @current_user.role.capitalize() %> <%= @current_user.email %></span>
    <%= link_to 'New Book', new_book_path, class: 'btn btn-primary mr-2' %>
    <%= link_to 'Librarian Dashboard', librarian_dashboard_path, class: 'btn btn-success mr-2' %>
    <%= link_to 'Logout', librarian_logout_path, method: :delete, class: 'btn btn-danger' %>
  </div>

  <% if @books.present? %>
    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Title</th>
          <th>Author</th>
          <th>Genre</th>
          <th>ISBN</th>
          <th>Total Copies</th>
          <th>All Time Borrowed</th>
          <th>Currently Borrowed</th>
          <th>Available Copies</th>
          <th>Actions</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.id %></td>
            <td><%= book.title %></td>
            <td><%= book.author %></td>
            <td><%= book.genre %></td>
            <td><%= book.isbn %></td>
            <td><%= book.total_copies %></td>
            <td><%= book.all_time_borrowed %></td>
            <td><%= book.currrently_borrowed %></td>
            <td><%= book.available_copies %></td>
            <td>
              <%= link_to 'Borrowings', book_borrowings_path(book), class: 'btn btn-success btn-sm' %>
            </td>
            <td>
              <%= link_to 'Show', book, class: 'btn btn-info btn-sm' %>
            </td>
            <td>
              <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning btn-sm' %>
            </td>
            <td>
              <%= form_with(model: book, url: book_path(book), method: :delete) do |form| %>
                <%= form.submit 'Remove', class: 'btn btn-danger btn-sm' %>
              <% end %>
            </td>       
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No books available.</p>
  <% end %>
</div>

app/views/books/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">New Book</h1>

  <%= form_with(model: @book, local: true) do |form| %>
    <div class="form-group">
      <%= form.label :title %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :author %>
      <%= form.text_field :author, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :genre %>
      <%= form.text_field :genre, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :isbn %>
      <%= form.text_field :isbn, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :total_copies %>
      <%= form.number_field :total_copies, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.submit 'Create Book', class: 'btn btn-primary' %>
      <%= link_to 'Cancel', books_path, class: 'btn btn-secondary' %>
    </div>
  <% end %>
</div>

app/views/books/show.html.erb
<div class="container mt-5">
  <h1 class="mb-4"><%= @book.title %></h1>

  <dl class="row">
    <dt class="col-sm-2">Author</dt>
    <dd class="col-sm-10"><%= @book.author %></dd>

    <dt class="col-sm-2">Genre</dt>
    <dd class="col-sm-10"><%= @book.genre %></dd>

    <dt class="col-sm-2">ISBN</dt>
    <dd class="col-sm-10"><%= @book.isbn %></dd>

    <dt class="col-sm-2">Total Copies</dt>
    <dd class="col-sm-10"><%= @book.total_copies %></dd>
  </dl>

  <div class="mt-3">
    <%= link_to 'Edit', edit_book_path(@book), class: 'btn btn-warning' %>
    <%= link_to 'Back to Books', books_path, class: 'btn btn-secondary' %>
  </div>
</div>